#!/usr/bin/env node
/**
 * Builds the Node-API addon from `crates/file-index-node` with `napi build --release`. Only
 * darwin-arm64 is a target (the index watches folders with FSEvents, and the native app ships
 * for Apple silicon only); other hosts skip the build and the loader then throws, which the
 * service reports as an unavailable search.
 *
 * The addon lands here as `file-index.darwin-arm64.node` (gitignored). The loader `index.js` and
 * the `index.d.ts` are generated by the same command and checked in, formatted with oxfmt, so
 * type checking works on hosts that skip the build.
 */
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

if (process.platform !== 'darwin' || process.arch !== 'arm64') {
  process.stdout.write(
    `Skipping the file-index addon: it builds for darwin-arm64 only, not ${process.platform}-${process.arch}.\n`,
  );
  process.exit(0);
}

const napi = spawnSync(
  'napi',
  [
    'build',
    '--release',
    '--platform',
    '--esm',
    '--manifest-path',
    '../../crates/file-index-node/Cargo.toml',
    '--output-dir',
    '.',
    '--js',
    'index.js',
    '--dts',
    'index.d.ts',
    // `Phase` becomes a string-literal union instead of a `const enum`, which the service's
    // isolated-modules compilation cannot import.
    '--no-const-enum',
  ],
  { cwd: packageRoot, stdio: 'inherit' },
);
if (napi.status !== 0) process.exit(napi.status ?? 1);
// Not `napi build --pipe`: that also pipes the binary through the command.
const format = spawnSync('oxfmt', ['index.js', 'index.d.ts'], {
  cwd: packageRoot,
  stdio: 'inherit',
});
process.exit(format.status ?? 1);
