// Generated by scripts/matte-layers.py from the Figma layer sheets. Do not edit by hand.
import { mediaUrl } from './media';

/** One layer of an interface scene, at 2x, positioned by case-layers.css. */
export interface CaseLayer {
  id: string;
  src: string;
  width: number;
  height: number;
}

export const caseDesktop = {
  src: mediaUrl('/cases/layers/desktop.webp'),
  width: 2880,
  height: 1800,
};

/** Each scene's layers, bottom to top. */
export const caseLayers = {
  'selection-toolbar': [
    {
      id: 'page',
      src: mediaUrl('/cases/layers/selection-toolbar/1-page.webp'),
      width: 1124,
      height: 444,
    },
    {
      id: 'highlight',
      src: mediaUrl('/cases/layers/selection-toolbar/2-highlight.webp'),
      width: 564,
      height: 48,
    },
    {
      id: 'text',
      src: mediaUrl('/cases/layers/selection-toolbar/3-text.webp'),
      width: 934,
      height: 78,
    },
    {
      id: 'toolbar',
      src: mediaUrl('/cases/layers/selection-toolbar/4-toolbar.webp'),
      width: 796,
      height: 160,
    },
  ],
  'mini-panel': [
    {
      id: 'flyout',
      src: mediaUrl('/cases/layers/mini-panel/1-flyout.webp'),
      width: 660,
      height: 462,
    },
    { id: 'rail', src: mediaUrl('/cases/layers/mini-panel/2-rail.webp'), width: 154, height: 488 },
    {
      id: 'pointer',
      src: mediaUrl('/cases/layers/mini-panel/3-pointer.webp'),
      width: 36,
      height: 44,
    },
  ],
  screenshot: [
    {
      id: 'windows',
      src: mediaUrl('/cases/layers/screenshot/1-windows.webp'),
      width: 2644,
      height: 1464,
    },
    { id: 'dim', src: mediaUrl('/cases/layers/screenshot/2-dim.webp'), width: 2880, height: 1800 },
    {
      id: 'mosaic',
      src: mediaUrl('/cases/layers/screenshot/3-mosaic.webp'),
      width: 436,
      height: 52,
    },
    {
      id: 'step-1',
      src: mediaUrl('/cases/layers/screenshot/4-step-1.webp'),
      width: 60,
      height: 60,
    },
    {
      id: 'step-2',
      src: mediaUrl('/cases/layers/screenshot/5-step-2.webp'),
      width: 108,
      height: 148,
    },
    {
      id: 'step-3',
      src: mediaUrl('/cases/layers/screenshot/6-step-3.webp'),
      width: 886,
      height: 172,
    },
    {
      id: 'selection',
      src: mediaUrl('/cases/layers/screenshot/7-selection.webp'),
      width: 1064,
      height: 972,
    },
    { id: 'bars', src: mediaUrl('/cases/layers/screenshot/8-bars.webp'), width: 1138, height: 260 },
    { id: 'hint', src: mediaUrl('/cases/layers/screenshot/9-hint.webp'), width: 776, height: 52 },
  ],
  'main-panel': [
    {
      id: 'panel',
      src: mediaUrl('/cases/layers/main-panel/1-panel.webp'),
      width: 1114,
      height: 1524,
    },
    {
      id: 'welcome',
      src: mediaUrl('/cases/layers/main-panel/2-welcome.webp'),
      width: 464,
      height: 102,
    },
  ],
  chat: [
    { id: 'panel', src: mediaUrl('/cases/layers/chat/1-panel.webp'), width: 1114, height: 1524 },
    { id: 'earlier', src: mediaUrl('/cases/layers/chat/2-earlier.webp'), width: 936, height: 332 },
    { id: 'ask', src: mediaUrl('/cases/layers/chat/3-ask.webp'), width: 612, height: 140 },
    { id: 'status', src: mediaUrl('/cases/layers/chat/4-status.webp'), width: 936, height: 48 },
    { id: 'tools', src: mediaUrl('/cases/layers/chat/5-tools.webp'), width: 926, height: 34 },
    { id: 'answer', src: mediaUrl('/cases/layers/chat/6-answer.webp'), width: 732, height: 128 },
    { id: 'actions', src: mediaUrl('/cases/layers/chat/7-actions.webp'), width: 288, height: 36 },
  ],
  settings: [
    {
      id: 'window',
      src: mediaUrl('/cases/layers/settings/1-window.webp'),
      width: 2164,
      height: 1604,
    },
    { id: 'page', src: mediaUrl('/cases/layers/settings/2-page.webp'), width: 1534, height: 1340 },
  ],
  apps: [
    { id: 'apps', src: mediaUrl('/cases/layers/apps/1-apps.webp'), width: 1004, height: 1324 },
    { id: 'notes', src: mediaUrl('/cases/layers/apps/2-notes.webp'), width: 1604, height: 1388 },
  ],
  automations: [
    {
      id: 'window',
      src: mediaUrl('/cases/layers/automations/1-window.webp'),
      width: 2164,
      height: 1604,
    },
    {
      id: 'page',
      src: mediaUrl('/cases/layers/automations/2-page.webp'),
      width: 1534,
      height: 1340,
    },
  ],
} satisfies Record<string, readonly CaseLayer[]>;
