/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1';

export declare class FileIndex {
  /** Opens (or creates) the index stored in `dataDir`. */
  static open(dataDir: string, options: OpenOptions): FileIndex;
  /** Starts watching and, when the saved state cannot be resumed, the first walk. */
  start(): void;
  /** Best matches first; `limit` is clamped to 1-100. */
  query(text: string, limit: number): Array<QueryHit>;
  status(): IndexStatus;
  /** Stops background work and saves the resume point. Also runs when the object is collected. */
  close(): void;
}

export interface IndexStatus {
  /** `idle` | `scanning` | `watching` | `stopped`. */
  phase: string;
  resumed: boolean;
  scannedFiles: number;
  /** FSEvents ids can exceed 2^53, so the id travels as a decimal string. */
  lastEventId: string;
  skippedRoots: Array<string>;
  error?: string;
}

export interface OpenOptions {
  /** Attachable extensions without dots, from the service's attachment rules. */
  extensions: Array<string>;
  /** Home folder to index; defaults to `$HOME`. iCloud Drive inside it is indexed as well. */
  home?: string;
}

export interface QueryHit {
  /** Stable per path across queries and restarts. */
  id: string;
  path: string;
  name: string;
  /** Home-relative parent folder, or under `iCloud Drive` ('' = home). */
  location: string;
  score: number;
  /** Epoch milliseconds. */
  modifiedAt?: number;
  /** Bytes. */
  size?: number;
  /** `[from, to)` UTF-16 offsets into `name.normalize('NFC')` where the query matched. */
  matchStart?: number;
  matchEnd?: number;
}
