/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1';

export declare class FileIndex {
  /**
   * Opens (or creates) the index stored in `dataDir`. Loading a large saved index takes a
   * moment, hence a promise.
   */
  static open(dataDir: string, options: OpenOptions): Promise<FileIndex>;
  /**
   * Starts watching and, when the saved state cannot be resumed, the first walk in the
   * background. Returns once the event stream runs.
   */
  start(): void;
  /**
   * Best matches first; `limit` is clamped to 1-100. Aborting `signal` rejects with an
   * `AbortError` while the query is still queued; a query that already runs finishes.
   */
  query(
    text: string,
    limit: number,
    signal?: AbortSignal | undefined | null,
  ): Promise<Array<QueryHit>>;
  status(): IndexStatus;
  /** Stops background work and saves the resume point. Also runs when the object is collected. */
  close(): Promise<void>;
}

export interface IndexStatus {
  phase: Phase;
  resumed: boolean;
  scannedFiles: number;
  /** FSEvents ids can exceed 2^53, so the id travels as a decimal string. */
  lastEventId: string;
  skippedRoots: Array<string>;
  error?: string;
}

export interface OpenOptions {
  /** Attachable extensions without dots, from the service's attachment rules. */
  extensions: Array<string>;
  /** Home folder to index; defaults to `$HOME`. iCloud Drive inside it is indexed as well. */
  home?: string;
}

/** Where the index is in its life. */
export type Phase = 'idle' | 'scanning' | 'watching' | 'stopped';

export interface QueryHit {
  /** Stable per path across queries and restarts. */
  id: string;
  path: string;
  name: string;
  /** Home-relative parent folder, or under `iCloud Drive` ('' = home). */
  location: string;
  score: number;
  /** Epoch milliseconds. */
  modifiedAt?: number;
  /** Bytes. */
  size?: number;
  /** `[from, to)` UTF-16 offsets into `name.normalize('NFC')` where the query matched. */
  matchStart?: number;
  matchEnd?: number;
}
